Repository milieuinfo/webcomponent-vl-ui-titles, pull requests merged in 2019-09, with the labels that each got.

#20 UIG-218
  vl-titles.src.js
Labels: maintenance

#21 Update link naar demo
  vl-titles.src.js
Labels: maintenance

#24 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#16 Update dependency vl-ui-core to v1.4.5
  package-lock.json
  package.json
Labels: dependencies

#9 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#27 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#26 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#25 Update dependency @govflanders/vl-ui-util to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#28 Update dependency vl-ui-core to v1.4.7
  package-lock.json
  package.json
Labels: dependencies

#32 UIG-143 - Update bamboo template
  CODEOWNERS
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
Labels: maintenance

#33 Update vl-ui-util
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  style.css
  style.css.map
Labels: maintenance
