Repository milieuinfo/webcomponent-vl-ui-titles, pull requests merged in 2020-06, with the labels that each got.

#67 Introductie vl-ui-demo en ESlint
  .eslintrc.json
  CODEOWNERS
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  demo/vl-titles.html
  index.js
  package-lock.json
  package.json
  src/index.js
  src/style.css
  src/style.css.map
  src/vl-titles.js
  test/e2e/components/vl-titles.js
  test/e2e/pages/vl-titles.page.js
  test/e2e/titles.test.js
  test/unit/vl-titles.test.html
Labels: chore

#68 Case van tekst was aangepast op de demo-pagina
  package-lock.json
  test/e2e/titles.test.js
Labels: bugfix

#71 Update dependency @govflanders/vl-ui-titles to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#73 Deduplicatie NPM run scripts
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  src/style.css
  test/docker-compose.yml
Labels: chore
