Repository milieuinfo/webcomponent-vl-ui-titles, pull requests merged in 2020-07, with the labels that each got.

#74 Update dependency @govflanders/vl-ui-util to v3.10.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#75 Introductie nieuw Vlaanderen icon font
  package-lock.json
  package.json
  src/style.css
  src/style.css.map
Labels: bug

#77 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore
