Repository milieuinfo/webcomponent-vl-ui-titles, pull requests merged in 2020-04, with the labels that each got.

#56 Update dependency vl-ui-util to v5.1.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#60 Update vl-ui-util
  .mocharc.js
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/e2e/button.test.js
  test/e2e/components/vl-button.js
  test/e2e/pages/vl-button.page.js
  test/unit/vl-button.test.html
Labels: chore

#61 Fix testen
  package-lock.json
  package.json
  test/e2e/button.test.js
  test/e2e/components/vl-button.js
  test/e2e/pages/vl-button.page.js
  test/unit/vl-button.test.html
Labels: bug

#62 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore

#63 Update dependency @govflanders/vl-ui-util to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate
